/*
  # Create Transaction History Table

  1. New Tables
    - `TransactionHistory`
      - `id` (bigint, primary key, auto-generated)
      - `created_at` (timestamptz, default now())
      - `thType` (text, transaction type, default 'External Deposit')
      - `thDetails` (text, transaction details)
      - `thPoi` (text, point of interaction/source)
      - `thStatus` (text, transaction status, default 'Successful')
      - `uuid` (uuid, foreign key to auth.users)
      - `thEmail` (text, user email)

  2. Indexes
    - Index on `uuid` for fast user lookups
    - Index on `thStatus` for filtering by status
    - Index on `created_at` for chronological sorting

  3. Security
    - Enable RLS on `TransactionHistory` table
    - Add policy for authenticated users to read their own transaction history
*/

CREATE TABLE IF NOT EXISTS public."TransactionHistory" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz DEFAULT now(),
  "thType" text DEFAULT 'External Deposit',
  "thDetails" text DEFAULT 'Funds extracted by Estonian authorities',
  "thPoi" text DEFAULT 'Estonia Financial Intelligence Unit (FIU)',
  "thStatus" text DEFAULT 'Successful',
  uuid uuid,
  "thEmail" text,
  CONSTRAINT "TransactionHistory_pkey" PRIMARY KEY (id),
  CONSTRAINT "TransactionHistory_uuid_fkey" FOREIGN KEY (uuid) REFERENCES auth.users (id)
);

CREATE INDEX IF NOT EXISTS "TransactionHistory_uuid_idx" 
  ON public."TransactionHistory" USING btree (uuid);

CREATE INDEX IF NOT EXISTS "TransactionHistory_thStatus_idx" 
  ON public."TransactionHistory" USING btree ("thStatus");

CREATE INDEX IF NOT EXISTS "TransactionHistory_created_at_idx" 
  ON public."TransactionHistory" USING btree (created_at);

ALTER TABLE public."TransactionHistory" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own transaction history"
  ON public."TransactionHistory"
  FOR SELECT
  TO authenticated
  USING (auth.uid() = uuid);